### PR TITLE
Added support for luacheck

### PR DESCRIPTION
**Pull request by DidierMalenfant**
This will also be supported in toybox.py v1.1 so that a toybox can bring its luacheck globals into a project using it.

Fixed some luacheck warning in AnimatedSprite.lua. Not sure if the line breaks in the docstring are ok or not.

### CODE REVIEW

**Comment by Whitebrim** [comment]
All changes to `AnimatedSprite.lua` doesn't look great for me, revert them and I'll merge.

**Comment by DidierMalenfant** [comment]
There are 3 types of changes that luacheck flagged for that file:

- Whitespace at the end of lines.
- Variable masking other variables.
- Lines that are too long.

Is there any of these 3 you can live with? First one and third ones are harmless but the second one should probably be fixed, no?

**Comment by Whitebrim** [comment]
> Variable masking other variables should probably be fixed, no?

I think you're right here, I have created new local varialble from argument - that makes no sense.
Can you remain changes on those two lines and configure luacheck to ignore file formatting for this file?

**Comment by DidierMalenfant** [comment]
No problem. Coming right up.

**Comment by DidierMalenfant** [comment]
Ok this should now have reverted the changes apart from the shadowed variables.

I will revisit adding some configuration to ignore the other warnings later. It's hard to find an elegant solution for this that works both in the project's folder and when the project is imported as a toybox.

**Comment by Whitebrim** [comment]
You've messed master and develop (less optimized with feature to skip frames if TickStep is < 1) branch code.
I've updated main .lua file in the repo, just create pr from master to master with additional luacheck files, thanks.

**Comment by DidierMalenfant** [comment]
My bad, I was trying to just do a PR from develop to develop.

Do I need to close this one and submit a whole new PR?

**Comment by Whitebrim** [comment]
If it works be easier

**Pull request closed without merging**
