### PR TITLE
Formatted README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  - `library`
  - `playdate`
  - `animation`
  - `sprites`

  <br>

- **Update Description**

  `Animated sprites library for @PlayDate`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`
  
  <br>
  
- ***[Why not to use GitHub Wiki][Wiki]***

  <br>

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Added license badge

- Added quicklinks

- Added social buttons

- Moved installation / performance into dedicated files

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/AnimatedSprite

### CODE REVIEW

**Comment by Whitebrim** [comment]
How appropriate is it to change the current description of the repository, excluding keywords from there?

**Comment by ElectronicsArchiver** [comment]
I'm not quite sure what you mean, could you elaborate?

**Comment by Whitebrim** [comment]
I already have description, that states: "Sprite class extension with imagetable and finite state machine support. Playdate specific." 
You suggest to change it to "Animated sprites library for @PlayDate"
My description gives better view for the repo...
I might change it to "Sprite class extension with imagetable animation and finite state machine support for @Playdate"

**Comment by ElectronicsArchiver** [comment]
Repository descriptions should be short and only give the main point of the project.
Thats why one elaborate in the README.

When people search for (in this case a library) they don't care about specifics, they in the first line would search for (in this case) the game -> playdate, second project type -> library, third library type -> animation (framework).

**Comment by Whitebrim** [comment]
> Repository descriptions should be short and only give the main point of the project. Thats why one elaborate in the README.
> 
> When people search for (in this case a library) they don't care about specifics, they in the first line would search for (in this case) the game -> playdate, second project type -> library, third library type -> animation (framework).

Repository descriptions should have keywords for search optimisations, readability is in second but not least place

**Comment by ElectronicsArchiver** [comment]
> Repository descriptions should have keywords for search optimisations, readability is in second but not least place

Thats why you have ~~tags~~ topics.

**Comment by ElectronicsArchiver** [comment]
You can add up to `20` btw.

**Comment by Whitebrim** [comment]
image
sorry

**Comment by ElectronicsArchiver** [comment]
What payment?

**Comment by Whitebrim** [comment]
> What payment?

You know every work must be rewarded...

**Comment by ElectronicsArchiver** [comment]
> > What payment?
> 
> You know every work must be rewarded...

O.O oh wow, well thank you for your consideration,
even if it didn't work, for whatever reason..

**Pull request merged**
